using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Threading.Tasks;
using MySynch.Common.IOC;
using MySynch.Common.Logging;
using MySynch.Common.Serialization;
using MySynch.Contracts;
using MySynch.Contracts.Messages;
using MySynch.Proxies.Autogenerated.Interfaces;

namespace MySynch.Core.Broker
{
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.Single)]
    public class Broker:IBroker
    {
        private IEnumerable<Registration> _registrations;
        private StoreType _store;
        private IStore<Registration> _storeHandler;
        private List<BrokerMessage> _receivedMessages;
        private MySynchComponentResolver _componentResolver;
        internal virtual SortedList<string, ISubscriberProxy> InitiatedSubScriberProxies { get; set; }
        private object _lock= new object();

        public GetHeartbeatResponse GetHeartbeat()
        {
            return new GetHeartbeatResponse {Status = true};
        }

        public Broker(StoreType storeType, MySynchComponentResolver componentResolver)
        {
            try
            {
                _store = storeType;
                _componentResolver = componentResolver;
                _storeHandler = _componentResolver.Resolve<IStore<Registration>>(storeType.StoreTypeName);
                _registrations =
                    _storeHandler.GetMethod(_store.StoreName);
                _receivedMessages=new List<BrokerMessage>();
                InitiatedSubScriberProxies= new SortedList<string, ISubscriberProxy>();
            }
            catch (ComponentNotRegieteredException ex)
            {
                LoggingManager.LogMySynchSystemError(ex);
                throw;
            }
            catch (Exception ex)
            {
                LoggingManager.LogMySynchSystemError(ex);
                _registrations = new List<Registration>();
            }
        }

        public AttachResponse Attach(AttachRequest request)
        {
            using (LoggingManager.LogMySynchPerformance())
            {
                if (request == null || request.RegistrationRequest == null ||
                    string.IsNullOrEmpty(request.RegistrationRequest.ServiceUrl))
                    return new AttachResponse {RegisteredOk = false};
                try
                {
                    if (_registrations.Any(r => r.ServiceUrl == request.RegistrationRequest.ServiceUrl))
                        return new AttachResponse {RegisteredOk = true};
                    _registrations =
                        _registrations.ToList().AddRegistration(request.RegistrationRequest).SaveAndReturn(
                            _store.StoreName, _storeHandler.StoreMethod);
                    return new AttachResponse {RegisteredOk = true};
                }
                catch (Exception ex)
                {
                    LoggingManager.LogMySynchSystemError(ex);
                    return new AttachResponse {RegisteredOk = false};
                }
            }
        }

        public DetachResponse Detach(DetachRequest request)
        {
            if(request==null || string.IsNullOrEmpty(request.ServiceUrl))
                return new DetachResponse{Status = false};
            try
            {
                if (!_registrations.Any(r => r.ServiceUrl == request.ServiceUrl))
                    return new DetachResponse { Status = false };
                _registrations =
                    _registrations.ToList().RemoveRegistration(request.ServiceUrl).SaveAndReturn(
                        _store.StoreName,_storeHandler.StoreMethod);
                return new DetachResponse { Status = true };
            }
            catch (Exception ex)
            {
                LoggingManager.LogMySynchSystemError(ex);
                return new DetachResponse { Status = false };
            }
        }

        public ListAllRegistrationsResponse ListAllRegistrations()
        {
            return new ListAllRegistrationsResponse {Registrations = _registrations.ToList()};
        }

        public void ReceiveAndDistributeMessage(ReceiveAndDistributeMessageRequest request)
        {
            var brokerMessage = request.PublisherMessage.ConvertToBrokerMessage();
            _receivedMessages.Add(brokerMessage);
            DistributeMessageToAllAvailableSubscribers(brokerMessage);
        }

        private void DistributeMessageToAllAvailableSubscribers(BrokerMessage brokerMessage)
        {
            var availableSubscribers =
                _registrations.Where(
                    r =>
                    r.ServiceRole == ServiceRole.Subscriber && r.OperationTypes.Contains(brokerMessage.OperationType));
            if (!availableSubscribers.Any())
                return;
            brokerMessage.Destinations =
                availableSubscribers.Select(
                    s => new Destination {DestinationUrl = s.ServiceUrl, ProcessedByDestination = false,ParentMessage=brokerMessage as PublisherMessage}).ToList();
            List<Task> tasks= new List<Task>();
            foreach (var destination in brokerMessage.Destinations)
            {
                Task task = new Task(()=>DistributeMessageToSubscriber(destination));
                tasks.Add(task);
                task.Start();
            }
        }

        private void DistributeMessageToSubscriber(object destination)
        {
            var subscriberRemote = GetOrCreateAProxy(((Destination) destination).DestinationUrl);
            ReceiveMessageRequest request=new ReceiveMessageRequest{PublisherMessage = ((Destination)destination).ParentMessage};
            var response = subscriberRemote.ReceiveMessage(request);
            ((Destination) destination).ProcessedByDestination = response.Success;
        }

        private ISubscriberProxy GetOrCreateAProxy(string destinationUrl)
        {
            lock (_lock)
            {
                if (InitiatedSubScriberProxies.ContainsKey(destinationUrl))
                    return InitiatedSubScriberProxies[destinationUrl];

                var subscriberRemote = _componentResolver.Resolve<ISubscriberProxy>("ISubscriber.Remote");
                subscriberRemote.InitiateUsingServerAddress(destinationUrl);
                InitiatedSubScriberProxies.Add(destinationUrl, subscriberRemote);
                return subscriberRemote;
            }
        }

        public ListAllMessagesResponse ListAllMessages()
        {
            return new ListAllMessagesResponse {AvailableMessages = _receivedMessages};
        }
    }
}
