using System;
using System.Collections.Generic;
using System.IO;
using System.ServiceModel;
using System.Threading;
using MySynch.Common.Logging;
using MySynch.Common.Serialization;
using MySynch.Contracts;
using MySynch.Contracts.Messages;
using MySynch.Core.DataTypes;
using MySynch.Core.Interfaces;
using MySynch.Proxies.Autogenerated.Interfaces;

namespace MySynch.Core.Publisher
{
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.Single)]
    public class PushPublisher:ILocalComponent,IPublisher
    {
        private IBrokerProxy _brokerClient;
        private FSWatcher _fsWatcher;
        private string _hostUrl;
        private object _lock= new object();
        private bool operationInProgress = false;

        #region Initialization Logic

        internal SynchItem CurrentRepository { get; set; }

        public void Initialize(IBrokerProxy brokerClient, LocalComponentConfig localComponentConfiguration, string hostUrl)
        {
            operationInProgress = true;
            LoggingManager.Debug("Initializing publisher with rootfolder: " + localComponentConfiguration.RootFolder);
            if (string.IsNullOrEmpty(localComponentConfiguration.RootFolder))
                LoggingManager.LogMySynchSystemError(new ArgumentNullException("localComponentConfiguration.RootFolder"));
            LoggingManager.Debug("Publisher initialized");
            _hostUrl = hostUrl;
            _brokerClient = brokerClient;
            _fsWatcher = new FSWatcher(localComponentConfiguration.RootFolder, QueueInsert, QueueUpdate, QueueDelete);
            operationInProgress = false;
        }
        #endregion

        #region Push Logic
        internal void QueueInsert(string absolutePath)
        {
            operationInProgress = true;
            if (string.IsNullOrEmpty(absolutePath))
                return;
            LoggingManager.Debug("Will queue an insert for: " + absolutePath);
            PublishMessage(absolutePath, OperationType.Insert);
            lock (_lock)
                UpdateCurrentRepository(absolutePath, OperationType.Insert);
            operationInProgress = false;

        }

        private void PublishMessage(string absolutePath, OperationType operationType)
        {
            ReceiveAndDistributeMessageRequest request = new ReceiveAndDistributeMessageRequest
                                                             {
                                                                 PublisherMessage = 
                                                                     new PublisherMessage
                                                                         {
                                                                             AbsolutePath = absolutePath,
                                                                             OperationType = operationType,
                                                                             SourceOfMessageUrl=_hostUrl,
                                                                             SourcePathRootName=_fsWatcher.Path 
                                                                         }
                                                             };
            _brokerClient.ReceiveAndDistributeMessage(request);
        }

        internal void QueueUpdate(string absolutePath)
        {
            operationInProgress = true;
            if (string.IsNullOrEmpty(absolutePath))
                return;
            LoggingManager.Debug("Will queue an update for: " + absolutePath);
            PublishMessage(absolutePath, OperationType.Update);
            lock (_lock)
                UpdateCurrentRepository(absolutePath, OperationType.Update);
            operationInProgress = false;
        }

        internal void QueueDelete(string absolutePath)
        {
            operationInProgress = true;
            if (string.IsNullOrEmpty(absolutePath))
                return;
            LoggingManager.Debug("Will queue a delete for: " + absolutePath);
            PublishMessage(absolutePath, OperationType.Delete);
            lock (_lock)
                UpdateCurrentRepository(absolutePath, OperationType.Delete);
            operationInProgress = false;
        }
        #endregion

        public void Close(object backupFileName=null)
        {
            while (operationInProgress)
                Thread.Sleep(500);

            Serializer.SerializeToFile(new List<SynchItem> { CurrentRepository }, (string)backupFileName);
        }

        #region Pull Logic
        public GetDataResponse GetData(GetDataRequest request)
        {
            operationInProgress = true;
            if (request == null || string.IsNullOrEmpty(request.FileName))
                throw new ArgumentNullException("request");
            if (!File.Exists(request.FileName))
                throw new ArgumentException("File does not exist " + request.FileName);
            LoggingManager.Debug("Using remote datasource returning contents of file: " + request.FileName);
            GetDataResponse response = new GetDataResponse();
            FileInfo fInfo = new FileInfo(request.FileName);
            response.Data = new byte[fInfo.Length];
            using (FileStream stream = fInfo.OpenRead())
            {
                stream.Read(response.Data, 0, response.Data.Length);
                stream.Flush();
            }
            operationInProgress = false;
            return response;
        }

        public GetHeartbeatResponse GetHeartbeat()
        {
            return new GetHeartbeatResponse {RootPath = _fsWatcher.Path, Status = true};
        }
        #endregion

        #region Persist traces for offline changes logic

        private void UpdateCurrentRepository(string absolutePath, OperationType operationType)
        {
            LoggingManager.Debug("Updating CurrentRepository with " + absolutePath);
            switch (operationType)
            {
                case OperationType.Insert:
                    SynchItemManager.AddItem(CurrentRepository, absolutePath, ItemDiscoverer.GetSize(absolutePath));
                    return;
                case OperationType.Update:
                    SynchItemManager.UpdateExistingItem(CurrentRepository, absolutePath, ItemDiscoverer.GetSize(absolutePath));
                    return;
                case OperationType.Delete:
                    SynchItemManager.DeleteItem(CurrentRepository, absolutePath);
                    return;

            }
        }



        #endregion
    }
}
