using MySynch.Contracts.Messages;
using MySynch.Proxies.Autogenerated.Implementations;
using NUnit.Framework;
using System.Collections.Generic;

namespace MySynch.Tests.Integration
{
    [TestFixture]
    [Ignore("These tests require the broker to be running on this machine")]
    public class BrokerAttachDetachTests
    {
        [Test]
        public void AttachToBrokerOk()
        {
            BrokerClient clientBuild=new BrokerClient();
            clientBuild.InitiateUsingServerAddress("http://sciendo-laptop/broker");
            AttachRequest request = new AttachRequest
                                        {
                                            RegistrationRequest =
                                                new Registration
                                                    {
                                                        OperationTypes =
                                                            new List<OperationType>
                                                                {OperationType.Insert, OperationType.Update},
                                                        ServiceRole = ServiceRole.Publisher,
                                                        ServiceUrl = "my service url"
                                                    }
                                        };
            var response = clientBuild.Attach(request);
            Assert.True(response.RegisteredOk);
        }

        [Test]
        public void DetachToBrokerOk()
        {
            BrokerClient clientBuild = new BrokerClient();
            clientBuild.InitiateUsingServerAddress("http://sciendo-laptop/broker");
            DetachRequest request = new DetachRequest
            {
                        ServiceUrl = "my service url"
            };
            var response = clientBuild.Detach(request);
            Assert.True(response.Status);
        }

        [Test]
        public void ReceiveAndDistributeMessagesOk()
        {
            BrokerClient clientBuild = new BrokerClient();
            clientBuild.InitiateUsingServerAddress("http://sciendo-laptop/broker");
            ReceiveAndDistributeMessageRequest request = new ReceiveAndDistributeMessageRequest
                                                             {
                                                                 PublisherMessage = 
                                                                     new PublisherMessage
                                                                         {
                                                                             AbsolutePath = "abc",
                                                                             OperationType = OperationType.Insert
                                                                         }
                                                             };
            clientBuild.ReceiveAndDistributeMessage(request);
            var response = clientBuild.ListAllMessages();
            Assert.IsNotNull(response);
            Assert.IsNotNull(response.AvailableMessages);
            Assert.AreEqual(1,response.AvailableMessages.Count);
        }
    }
}
