using System.IO;
using MySynch.Contracts.Messages;
using MySynch.Proxies.Autogenerated.Implementations;
using MySynch.Proxies.Autogenerated.Interfaces;
using NUnit.Framework;

namespace MySynch.Tests.Integration
{
    //[TestFixture]
    //[Category("integration")]
    //[Ignore("Start the services at the specified address and after that this should run")]
    //public class FullIntegrationTests
    //{
        //    [Test]
        //public void PublisherStartsWithoutABackupFile()
        //{
        //    ServiceController serviceController = new ServiceController("MySynch.Publisher.Debug");
        //    serviceController.Stop();
        //    serviceController.WaitForStatus(ServiceControllerStatus.Stopped, TimeSpan.FromSeconds(10));

        //    if (File.Exists(@"C:\Code\Sciendo\MySynch\MySynch.Publisher\bin\Debug\backup.xml"))
        //        File.Delete(@"C:\Code\Sciendo\MySynch\MySynch.Publisher\bin\Debug\backup.xml");

        //    serviceController.Start();
        //    serviceController.WaitForStatus(ServiceControllerStatus.Running, TimeSpan.FromSeconds(10));

        //    BrokerClient publisherProxy = new BrokerClient();
        //    publisherProxy.InitiateUsingServerAddress(@"http://localhost/publisher");
        //    var publishedPackage = publisherProxy.PublishPackage();
        //    Assert.IsNull(publishedPackage);

        //}

        //[Test]
        //public void PublisherStartsWithABackupFile()
        //{
        //    ServiceController serviceController = new ServiceController("MySynch.Publisher.Debug");
        //    serviceController.Stop();
        //    serviceController.WaitForStatus(ServiceControllerStatus.Stopped, TimeSpan.FromSeconds(10));

        //    File.Copy(@"Data\XMLFile2.xml", @"C:\MySynch.Source.Test.Root\XMLFile2.xml", true);

        //    File.Copy(@"Data\backup.xml", @"C:\Code\Sciendo\MySynch\MySynch.Publisher\bin\Debug\backup.xml", true);
        //    serviceController.Start();
        //    serviceController.WaitForStatus(ServiceControllerStatus.Running, TimeSpan.FromSeconds(10));

        //    IPublisherProxy publisherProxy = new PublisherClient();
        //    publisherProxy.InitiateUsingPort(8765);
        //    var publishedPackage = publisherProxy.PublishPackage();
        //    Assert.IsNotNull(publishedPackage);
        //    Assert.AreEqual(5, publishedPackage.ChangePushItems.Count);
        //    Assert.AreEqual(1,
        //                    publishedPackage.ChangePushItems.Count(
        //                        i =>
        //                        i.OperationType == OperationType.Update &&
        //                        i.AbsolutePath == @"C:\MySynch.Source.Test.Root\abc\abc def\def feg\abc cba.txt"));
        //    Assert.AreEqual(1,
        //                    publishedPackage.ChangePushItems.Count(
        //                        i =>
        //                        i.OperationType == OperationType.Insert &&
        //                        i.AbsolutePath == @"C:\MySynch.Source.Test.Root\XMLFile2.xml"));

        //    serviceController.Stop();
        //    serviceController.WaitForStatus(ServiceControllerStatus.Stopped, TimeSpan.FromSeconds(10));
        //    File.Delete(@"C:\Code\Sciendo\MySynch\MySynch.Publisher\bin\Debug\backup.xml");
        //    File.Delete(@"C:\MySynch.Source.Test.Root\XMLFile2.xml");
        //}

    //    [Test]
    //    [Ignore(@"Requires Subscriber service to be defined on the root folder: C:\MySynch.Dest.Test.Root\ and publisher on C:\MySynch.Source.Test.Root\")]
    //    public void DistributorUpAndAccessible()
    //    {
    //        IDistributorMonitorProxy distributorMonitorProxy = new DistributorMonitorClient();
    //        distributorMonitorProxy.InitiateUsingPort(8765);
    //        var listAvailableChannels = distributorMonitorProxy.ListAvailableChannels();
    //        Assert.IsNotNull(listAvailableChannels);
    //        Assert.AreEqual("SCIENDO-LAPTOP", listAvailableChannels.Name);
    //        Assert.AreEqual(1, listAvailableChannels.Channels.Count);
    //        Assert.AreEqual("IPublisher.Remote", listAvailableChannels.Channels[0].PublisherInfo.InstanceName);
    //        Assert.AreEqual(8765, listAvailableChannels.Channels[0].PublisherInfo.Port);
    //        Assert.AreEqual(Status.Ok, listAvailableChannels.Channels[0].Status);
    //        Assert.IsNull(listAvailableChannels.Channels[0].PublisherInfo.CurrentPackage);
    //        Assert.IsNotNull(listAvailableChannels.Channels[0].SubscriberInfo);
    //        Assert.AreEqual("ISubscriber.Remote", listAvailableChannels.Channels[0].SubscriberInfo.InstanceName);
    //        Assert.AreEqual(8765,listAvailableChannels.Channels[0].SubscriberInfo.Port);
    //        Assert.AreEqual(Status.Ok, listAvailableChannels.Channels[0].SubscriberInfo.Status);
    //        Assert.AreEqual(@"C:\MySynch.Dest.Test.Root\", listAvailableChannels.Channels[0].SubscriberInfo.RootPath);
    //        Assert.IsNull(listAvailableChannels.Channels[0].SubscriberInfo.CurrentPackage);
    //    }

    //    [Test]
    //    public void DistributorDistreibuteMessage_Ok()
    //    {
    //        if (File.Exists(@"C:\MySynch.Dest.Test.Root\File1.xml"))
    //            File.Delete(@"C:\MySynch.Dest.Test.Root\File1.xml");
    //        IDistributorMonitorProxy distributorMonitorProxy = new DistributorMonitorClient();
    //        distributorMonitorProxy.InitiateUsingPort(8765);
    //        var listOfComponents = distributorMonitorProxy.ListAvailableChannels();
    //        Assert.IsNotNull(listOfComponents);
    //        File.Copy(@"Data\File1.xml", @"C:\MySynch.Source.Test.Root\File1.xml", true);
            
    //    }
    //}
}
