using System.IO;
using MySynch.Contracts.Messages;
using MySynch.Proxies.Autogenerated.Implementations;
using MySynch.Proxies.Autogenerated.Interfaces;
using NUnit.Framework;

namespace MySynch.Tests.Integration
{
    [TestFixture]
    [Category("integration")]
    [Ignore("Start the servives at the specified address and after that this should run")]
    public class SubscriberTests
    {
        [Test]
        public void SubscriberUpAndAccessible()
        {
            ISubscriberProxy subscriberProxy = new SubscriberClient();
            subscriberProxy.InitiateUsingServerAddress(@"http://localhost/subscriber/");
            Assert.True(subscriberProxy.GetHeartbeat().Status);
            Assert.IsNotNull(subscriberProxy.GetHeartbeat().RootPath);
        }

        [Test]
        [Ignore(@"Assumes presence of C:\MySynch.Source.Test.Root\File1.xml")]
        public void TestOnlyRemoteDataSource_Ok()
        {
            if (File.Exists(@"C:\MySynch.Dest.Test.Root\File1.xml"))
                File.Delete(@"C:\MySynch.Dest.Test.Root\File1.xml");
            SubscriberClient subscriber = new SubscriberClient();
            subscriber.InitiateUsingServerAddress(@"http://localhost/subscriber/");
            PublisherMessage publisherMessage = new PublisherMessage
            {
                SourceOfMessageUrl = @"http://sciendo-laptop/publisher",
                SourcePathRootName = @"C:\MySynch.Source.Test.Root\",
                AbsolutePath = @"C:\MySynch.Source.Test.Root\File1.xml",
                OperationType = OperationType.Insert
            };

            Assert.True(subscriber.ReceiveMessage(new ReceiveMessageRequest { PublisherMessage = publisherMessage }).Success);
            Assert.True(File.Exists(@"C:\MySynch.Dest.Test.Root\File1.xml"));
        }
    }
}
