using MySynch.Core.DataTypes;
using MySynch.Proxies.Autogenerated.Interfaces;

namespace MySynch.Core.Interfaces
{
    public interface ILocalComponent
    {
        void Initialize(IBrokerProxy brokerClient, LocalComponentConfig localComponentConfig, string hostUrl);

        void Close(object objectState=null);
    }
}
