using MySynch.Contracts;
using MySynch.Core.Configuration;
using MySynch.Proxies.Autogenerated.Interfaces;

namespace MySynch.Core.Interfaces
{
    public interface ILocalComponent:IComponentMonitor
    {
        void Initialize(IBrokerProxy brokerClient, MySynchLocalComponentConfigurationSection localComponentConfig, string hostUrl);

        void Close(object objectState=null);

    }
}
