//This code was auto generated with a tool
//do not change this file
using MySynch.Contracts;
using MySynch.Common.WCF.Clients;

namespace MySynch.Proxies.Autogenerated.Interfaces
{
	public interface IBrokerProxy:IBroker,IInitiateClient 
	{

	}
}
