//This code was auto generated with a tool
//do not change this file
using MySynch.Contracts;
using Sciendo.Common.WCF.Clients;

namespace MySynch.Proxies.Autogenerated.Interfaces
{
	public interface IComponentMonitorProxy:IComponentMonitor,IInitiateClient 
	{

	}
}
