using Moq;
using MySynch.Proxies.Autogenerated.Implementations;

namespace MySynch.Tests
{
    internal static class MockTestHelper
    {
        public static BrokerClient MockBrokerClient()
        {
            var mockBrokerClient = new Mock<BrokerClient>();
            return mockBrokerClient.Object;
        }
    }
}
