using System;
using MySynch.Contracts.Messages;
using MySynch.Proxies.Autogenerated.Interfaces;

namespace MySynch.Tests.Stubs
{
    public class MockRemotePublisherNotPresent:IPublisherProxy
    {
        public GetHeartbeatResponse GetHeartbeat()
        {
            return new GetHeartbeatResponse {Status = false};
        }

        public GetDataResponse GetData(GetDataRequest request)
        {
            throw new NotImplementedException();
        }

        public void InitiateUsingServerAddress(string serverAddress)
        {
            throw new NotImplementedException();
        }

        public void Reset()
        {
            throw new NotImplementedException();
        }
    }
}
