using System;
using System.ServiceModel;
using MySynch.Contracts.Messages;
using MySynch.Proxies.Autogenerated.Interfaces;

namespace MySynch.Tests.Stubs
{
    public class MockRemoteBroker:IBrokerProxy
    {
        public GetHeartbeatResponse GetHeartbeat()
        {
            throw new NotImplementedException();
        }

        public AttachResponse Attach(AttachRequest request)
        {
            throw new NotImplementedException();
        }

        public DetachResponse Detach(DetachRequest request)
        {
            throw new NotImplementedException();
        }

        public void ReceiveAndDistributeMessage(ReceiveAndDistributeMessageRequest request)
        {
            throw new NotImplementedException();
        }

        public void MessageReceivedFeedback(MessageReceivedFeedbackRequest request)
        {
            ;
        }

        public void InitiateUsingServerAddress(string serverAddress)
        {
            throw new NotImplementedException();
        }

        public void InitiateDuplexUsingServerAddress(string serverAddress, InstanceContext callbackInstance)
        {
            throw new NotImplementedException();
        }

        public void Reset()
        {
            throw new NotImplementedException();
        }
    }
}
