using System;
using System.ServiceModel;
using MySynch.Contracts.Messages;
using MySynch.Proxies.Autogenerated.Interfaces;

namespace MySynch.Tests.Stubs
{
    internal class MockRemoteSubscriberNotPresent:ISubscriberProxy
    {
        public GetHeartbeatResponse GetHeartbeat()
        {
            return new GetHeartbeatResponse {Status = false};
        }

        public ReceiveMessageResponse ReceiveMessage(ReceiveMessageRequest request)
        {
            throw new NotImplementedException();
        }

        public void InitiateUsingServerAddress(string serverAddress)
        {
            throw new NotImplementedException();
        }

        public void InitiateDuplexUsingServerAddress(string serverAddress, InstanceContext callbackInstance)
        {
            throw new NotImplementedException();
        }
        public void Reset()
        {
            return;
        }
    }
}
