using System;
using MySynch.Contracts.Messages;
using MySynch.Proxies.Autogenerated.Interfaces;

namespace MySynch.Tests.Stubs
{
    public class MockRemoteSubscriber:ISubscriberProxy
    {
        private string targetRootFolder;

        public GetHeartbeatResponse GetHeartbeat()
        {
            return new GetHeartbeatResponse { Status = true, RootPath = "It'smy party" };
        }
        public ReceiveMessageResponse ReceiveMessage(ReceiveMessageRequest request)
        {
            if (targetRootFolder == "wrong folder")
                throw new Exception();
            return new ReceiveMessageResponse
                       {
                           Success = copyMethod("abc", "def")
                       };
        }


        private bool copyMethod(string absolutePath, string replace)
        {
            return true;
        }

        public void InitiateUsingServerAddress(string serverAddress)
        {
            ;
        }

        public void Reset()
        {
            throw new NotImplementedException();
        }
    }
}
