//This code was auto generated with a tool
//do not change this file
using System;
using System.ServiceModel;
using MySynch.Contracts;
using Sciendo.Common.WCF;
using Sciendo.Common.WCF.Clients;
using MySynch.Proxies.Autogenerated.Interfaces;
using System.ServiceModel.Description;
using System.Collections.Generic;


namespace MySynch.Proxies.Autogenerated.Implementations
{
	public class BrokerClient :BaseClient<IBroker>,IBrokerProxy
	{
		protected override System.Collections.Generic.List<System.ServiceModel.Description.IEndpointBehavior> GetEndpointBehaviors()
        {
            return new List<IEndpointBehavior>
			{
							new SciendoAuditBehavior()
			};
        }

		public MySynch.Contracts.Messages.GetHeartbeatResponse GetHeartbeat() 
		{
		MySynch.Contracts.Messages.GetHeartbeatResponse response = new MySynch.Contracts.Messages.GetHeartbeatResponse(); 
		try
		{
		                using (new OperationContextScope((IContextChannel)Proxy))
                {
				 response =  
					Proxy.GetHeartbeat();
				}
		}
		catch (CommunicationException e)
            {
                OnCommunicationException(e);
            }
            catch (TimeoutException e)
            {
                OnTimeoutException(e);
            }
            catch (Exception e)
            {
                OnException(e);
            }

			return  response; 

		}
		public MySynch.Contracts.Messages.AttachResponse Attach(MySynch.Contracts.Messages.AttachRequest request) 
		{
		MySynch.Contracts.Messages.AttachResponse response = new MySynch.Contracts.Messages.AttachResponse(); 
		try
		{
		                using (new OperationContextScope((IContextChannel)Proxy))
                {
				 response =  
					Proxy.Attach(request);
				}
		}
		catch (CommunicationException e)
            {
                OnCommunicationException(e);
            }
            catch (TimeoutException e)
            {
                OnTimeoutException(e);
            }
            catch (Exception e)
            {
                OnException(e);
            }

			return  response; 

		}
		public MySynch.Contracts.Messages.DetachResponse Detach(MySynch.Contracts.Messages.DetachRequest request) 
		{
		MySynch.Contracts.Messages.DetachResponse response = new MySynch.Contracts.Messages.DetachResponse(); 
		try
		{
		                using (new OperationContextScope((IContextChannel)Proxy))
                {
				 response =  
					Proxy.Detach(request);
				}
		}
		catch (CommunicationException e)
            {
                OnCommunicationException(e);
            }
            catch (TimeoutException e)
            {
                OnTimeoutException(e);
            }
            catch (Exception e)
            {
                OnException(e);
            }

			return  response; 

		}
		public void ReceiveAndDistributeMessage(MySynch.Contracts.Messages.ReceiveAndDistributeMessageRequest request) 
		{
		 
		try
		{
		                using (new OperationContextScope((IContextChannel)Proxy))
                {
				 
					Proxy.ReceiveAndDistributeMessage(request);
				}
		}
		catch (CommunicationException e)
            {
                OnCommunicationException(e);
            }
            catch (TimeoutException e)
            {
                OnTimeoutException(e);
            }
            catch (Exception e)
            {
                OnException(e);
            }

			return ; 

		}
		public void MessageReceivedFeedback(MySynch.Contracts.Messages.MessageReceivedFeedbackRequest request) 
		{
		 
		try
		{
		                using (new OperationContextScope((IContextChannel)Proxy))
                {
				 
					Proxy.MessageReceivedFeedback(request);
				}
		}
		catch (CommunicationException e)
            {
                OnCommunicationException(e);
            }
            catch (TimeoutException e)
            {
                OnTimeoutException(e);
            }
            catch (Exception e)
            {
                OnException(e);
            }

			return ; 

		}
	}
}
		